# POST http://localhost:8000/api/v1/user/login
# Content-Type: application/json

# {
#     "name": "kaizar",
#     "password": "admin123",
#     "email": "kaizar123@gmail.com"
# }

GET http://localhost:8000/api/v1/discussion/comments/1 
Content-Type: application/json

{
    "sender": "6415a1fc5960b32eed0eb259",
    "_id": "1",
    "comment": "Comment 1"
}

# POST  http://localhost:3000/api/v1/user/add/profile-pic
# Content-Type: application/json

# {
#     "_id": "6415a1fc5960b32eed0eb259"
# }

# GET http://localhost:8000/api/v1/user/all-user

# PUT http://localhost:3000/api/v1/singleChat/message 
# Content-Type: application/json

# {
#     "sender": "6415a1fc5960b32eed0eb259",
#     "receiver": "6415e895ea02f939fd78951c",
#     "message": "message4"
# }

# GET http://localhost:3000/api/v1/singleChat/allChats

# GET http://localhost:3000/api/v1/singleChat/getChat/6415e888ea02f939fd789519

# GET http://localhost:3000/api/v1/singleChat/message/6416a085e8d6e738dc4af74d/6415e895ea02f939fd78951c

# GET http://localhost:3000/api/v1/groupChat/allChats

# POST http://localhost:3000/api/v1/groupChat/create/chat
# Content-Type: application/json

# {
#     "name": "textify2",
#     "admin": "6415a1fc5960b32eed0eb259",
#     "members": ["6415e888ea02f939fd789519"],
#     "isPrivate": true
# }

# GET http://localhost:3000/api/v1/groupChat/message/6416e36e763cd2e17840ecf3/6415a1fc5960b32eed0eb259

# POST http://localhost:3000/api/v1/groupChat/message
# Content-Type: application/json

# {
#     "_id": "5416e36e763cd2e17840ecf3",
#     "sender": "6415a1fc5960b32eed0eb259",
#     "message": "Group Chat Message2"
# }

# POST http://localhost:3000/api/v1/groupChat/change/admin
# Content-Type: application/json

# {
#     "_id": "6416e36e763cd2e17840ecf3",
#     "sender": "6415a1fc5960b32eed0eb259",
#     "newAdmin": "6415e888ea02f939fd789519"
# }

# POST http://localhost:3000/api/v1/groupChat/member
# Content-Type: application/json

# {
#     "_id": "6416e4d3627c4eae40af132d",
#     "sender": "64159fc37cbd82c531a727bb",
#     "newMember": "64159fc37cbd82c531a727bb"
# }

# DELETE  http://localhost:3000/api/v1/groupChat/delete/member/6416e36e763cd2e17840ecf3/6415e888ea02f939fd789519

# POST http://localhost:3000/api/v1/groupChat/change/visibilty
# Content-Type: application/json

# {
#     "_id": "6416e36e763cd2e17840ecf3",
#     "sender": "6415a1fc5960b32eed0eb259"
# }
